### ISSUE TITLE
Include Alice in Wonderland Stylised graphics 

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha-2-docs#84]
In-keeping with the style of the text and the prevalence of *execute* @outoftardis suggested that we add some Alice in Wonderland-styled graphics. 

We need something very schematic, preferably in the style of a book illustration that could be put as a watermark on the page, rather than a graphic. 

Drawings that we need
- [ ] Red queen ordering an execution
- [ ] White rabbit with a pocket watch
- [ ] As separate characters
  - [ ] Alice, 
  - [ ] Mad Hatter, 
  - [ ] March Hare, 
  - [ ] Dormouse
  - [ ] Playing cards
- [ ] Alice and Mad Hatter's tea party, where the Mad Hatter pours too much tea into Alice's cup.

**Comment by outoftardis** [comment]
low priority
